name: Test run
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: mvn clean package
        run: ./mvnw clean package

      - name: build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: yinan9751/moon-ladder:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yinan9751
          password: Docker824!

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yinan9751/moon-ladder:{{ github.sha }}

