name: Test run
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Maven package
        run: ./mvnw package

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yinan9751
          password: Docker824!

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yinan9751/moon-ladder:${{ github.sha }}

      - name: Print image version
        run: echo ${{ github.sha }}

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: yinan97/environment
          path: moon-ladder

      - name: Modify file in target repository
        run: |
          cd moon-ladder
          echo "Modified content" > file.txt
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add file.txt
          git commit -m "Modify file using GitHub Actions"
          git push


